# Generated by Django 3.2.5 on 2021-08-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectAPI.topic'),
        ),
    ]
